### ISSUE TITLE
Forum menu re-order: 

### ISSUE THREAD

**Issue by turukawa** [whythawk/hrd#101]
Could we look into "grouping" or highlighting the following:

- Resource search
- Member database search
- Message posting

On the menu bar in some way (without wrecking the theme) to make it easier for the user to spot the main tasks they may wish to perform. If that proves difficult, just describe the problem.

**Comment by tobes** [comment]
@ratkins5 

Is this referring to the main menu? like on the home page?

It is possible to move the 'message board' into the main menu is this what is wanted?

I can also make 'special pages' have a style eg we could make them bold. but might be worth getting a nice style.   Special pages are 'search resources', 'search members' & 'message board'

**Comment by ratkins5** [comment]
@tobes 

This relates to the change request line item 18 on the google spreadsheet 'Change Requests'.  

That says "The placement of “message board” should be together with “resources” and “search members.”  I was thinking:  searching for resources, searching the member database, and posting a message are the three main big functions of the protected part of the website.  Maybe these three functions could be better highlighted, maybe on their own menu line? ".

My read on this is that it means no more than shifting the 'Message Board' menu item to the left so it's close to the other items rather than out on its own.

**Comment by ratkins5** [comment]
@tobes 

I think the client would like the 'Special Pages' idea, but like you I think that it would be best to have it properly designed, or we risk degrading the design feel with add-on changes.

**Comment by tobes** [comment]
the 'menu redesign' would be separate to making it a special page, so no dependency.

shall I just bold them for now too ?

**Comment by ratkins5** [comment]
@tobes 

Yes, agreed.

**Comment by tobes** [comment]
live and updated - we can improve the styling as a different issue for now is bolder

**Comment by ratkins5** [comment]
Thanks Toby.  Yes, styling can be looked at separately.
