### ISSUE TITLE
"Latest news" added to the home page

### ISSUE THREAD

**Issue by turukawa** [whythawk/hrd#102]

**Comment by tobes** [comment]
@ratkins5 

do we know what 'latest news' actually is?

It feels that they want have a new form where they can add a news item (title, text - some document #104 ) that then gets shown say on home page.  Is this correct?

What about different languages?  would each have it's own separate news?

**Comment by tobes** [comment]
My take,

We add a new content admin bit to add news.

news is separate for each language - ie add for each language independently

**news has:**
* title
* some text
* optional uploaded file (only one per news item)

news can be edited and made active/inactive so out of date news can be removed

**news page:**
displays the full news item - good for long ones

**news visible**
On home page (or all content pages?) the most recently added news for the language is shown.

other option (show also show other news that is within x days old)

extra option (pin some news so it is always shown)

**news listing page:**
shows all (active) news for language newest first

**general**
showing news on all but full news page would truncate long news items and link to the full news

a better option might just be to display the title except on news listing page and news page

**landing page**
if we add #99 or similar maybe the 'latest' news should be there rather than on content pages

**Comment by ratkins5** [comment]
@tobes 

Your take on it seems well-thought-through to me, and would give us a better news function all round.  The request to show 'latest news' is that they want the most recent items to be shown on the home page (i.e. not requiring click-through to News).  It seems to me that that would be hard to do at all without the upgrades you've described above, though.

**Comment by tobes** [comment]
@ratkins5 

I'm almost done with this.  We are running out of menu space and having 2 news pages is confusing.

We have 2 options

1. Add new functionality, add news to it, then swap the 'new' news page for the 'cms' news page at some future date.

2. Just switch straight to 'new' news page(s) and news will appear as it is added.


Let me know which you prefer. I aim to get this live over the weekend.

**Comment by ratkins5** [comment]
@tobes 

If it's reasonably possible to revert in the event that they don't like it, my vote is to go with (1) above.

I don't know that we pinned it down, but I'd be more in favour of having any news feed on the home page but not repeating it on the other pages.   You've seen it, you've moved on, it's just annoying to keep seeing it.
